language: node_js
node_js:
  - "8"
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - npm install
  - echo 'Testing!'
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "F/Ep7r5zxQ80XOMh8tcvRJFGmnVAa9lwgFBzsDC2OR9mY+X6zDzqQ1Wa8xNHT3xvy/DZF96vWwZ4ncpf81BTPMcq1a8UFUnaf0vk6oxOgnTroQy6or1P+p6KATilHntcZTDEwFRy+s0uBhviKXzSwVFT8U2rJtqhbpw4TY+0MtfDmafNRViyPTYYsuSi/mswxPYsp6w+JSSrGyeDx/8y/OBGghJEYizkpEZcCkzQqRfTRNAynTpv7kzpQhoGCVyWCVENwH1/EQf0kR85PlTUSJTRKVwpaRDdf08RPUF49osB4YyYIc7GimBczfdI74+kPCr40HWzQ1D6Jf5j0g3bazvXeBU1vd9FqsrSyvfbS56nsSOGJ9JlzL6k3s8HvwoFzgR5YWJovNzdlaJj+ZyG+N+nJTbiBUm7GaMyGbAfo9L86yoVwG3KqA1ronh+VV9n4T/NmM/hJLblMMzwBeui9jfQnOJnJFxFs4XlxvwCNdJLatFyjOPdqzuPwQziXHM2tzAZam5y9mKXk+8msiKSSdhPtP7irqywP3NVzHQRnIT+Lh9HAbUd8bA3y70tWOrLZwLT2/7AUsimgxM9o3nm+3Nk9aIosWbCTHweoE5GbITwReaDVv9OZuoouDq+uKuw4O+NDOHbRdzxzDPs+Vln+1RNcBdu8DgF5+rfOG65e/4="