language: node_js
node_js:
  - "8"
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - yarn
  - echo 'Testing!'
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "rE/vPjtyhpwv4/wwqpi4QVWSPIHgF0jQUb2322mWykFtrow+oIgR04Ac0hBDk1V28eLFFqy0vWDq/SU+84SlazUjivOEiqqLFABVJkjvzMJuBuzvVi2hEnRt2PKU+maokNCTb0H0BSsqMjoLsJMPAi8MjPZ6KIE9UeUQTIxy2/4H054t/PEnbqJuOlCsTMb2B6EILDhcrhaGJhs/e1EADXIMMWDRXYgdchqWB5tgcYcddbHUTLMC87Ko8S1HSB9k2Vyhz9VmOuWsrp5ruS2S7j7XIpTVKMokYMlhdJWGfvZfchotGB0ZVYMtH5P+GPedn6Awiutu8SQMNyhpx7tbZTXsY9tEaSPp4Rq31n+zF/Pa7ys715brdsT3FI2gqpVnoh4Jd7dtwRQN29bT0yqPP+aL4KIFNnGhldd5BH6pXQCHGQlH0HPjGIEzNSGdCQKVoLHeGq2JOKfw8teVnEplUhEqO0w4iW5NoxiB8H+1+afyW1u8CDB8EMd++zlq2tm291UAeen6YA8A3N63Hf7RgKKL5Rp3w2zFTt5lO9vzc3Dzvvlkk3UIpXlx8N2e2VelsE5TQFz2nTuC1l1Ef3cQqa829Z1alDf1zEvu+n5jlBhB3dwCag4EGBMtLAwwVMkXt2sx1DwsWpNU/73Lq24w0EpJxEQ/esCGgKW3NIAc9xo="